### ISSUE TITLE
Add tests to increase coverage

### ISSUE THREAD

**Issue by rsmith013** [cedadev/stac-fastapi-elasticsearch#27]
Can use similar tests from here: 
https://github.com/stac-utils/stac-fastapi/tree/master/stac_fastapi/sqlalchemy/tests

**Comment by ellesmith88** [comment]
Added api tests:

A few things to note.

- I've added a geometry field to items.json as well as date because it says in the item spec 'STAC compliant APIs are required to compute intersection operations with the Item's geometry field, not its bbox.'

- at the moment the datetime query only works when datetime is defined in the item (rather than start_datetime and end_datetime being defined in the item). Haven't worked out how to identify which option is used.

-  The 3d bbox test doesn't work because the Coordinates class in models/utils.py only expects four coordinates. This needs to be extended.

**Comment by rsmith013** [comment]
great, thanks. I am not sure if elasticsearch can handle a 3D bounding box query.
